/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AdminTimoStatsRouteImport } from './routes/admin-timo-stats'
import { Route as IndexRouteImport } from './routes/index'

const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimoStatsRoute = AdminTimoStatsRouteImport.update({
  id: '/admin-timo-stats',
  path: '/admin-timo-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-timo-stats': typeof AdminTimoStatsRoute
  '/download': typeof DownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-timo-stats': typeof AdminTimoStatsRoute
  '/download': typeof DownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-timo-stats': typeof AdminTimoStatsRoute
  '/download': typeof DownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin-timo-stats' | '/download'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-timo-stats' | '/download'
  id: '__root__' | '/' | '/admin-timo-stats' | '/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminTimoStatsRoute: typeof AdminTimoStatsRoute
  DownloadRoute: typeof DownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-timo-stats': {
      id: '/admin-timo-stats'
      path: '/admin-timo-stats'
      fullPath: '/admin-timo-stats'
      preLoaderRoute: typeof AdminTimoStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminTimoStatsRoute: AdminTimoStatsRoute,
  DownloadRoute: DownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
